### PR TITLE
fix #161 allowing only limited elastic requests to be passed through

### LINKED ISSUE #161: Django should reject /elasticsearch requests other than GET on certain URLs
Maybe only allow `_msearch` and the `weedid` index.

### PR DESCRIPTION
**Pull request by jnothman**
Fixes #161

### CODE REVIEW

**Review by ElevnLi — APPROVED** [review]

**Comment by jnothman** [comment]
You've checked this works?

**Comment by jnothman** [comment]
No, this is incorrect. It needs to check for `/weedid/_msearch`.

**Comment by ElevnLi** [comment]
> No, this is incorrect. It needs to check for `/weedid/_msearch`.

`request.path` is /elasticsearch/weedid/_msearch, so `elasticsearch_url = "/".join(request.path.split("/")[3:])` should be `/_msearch`.
I think current setup is fine, filtering out DELETE method and only keeping multi search for GET and POST, so we don't have to worry about things like [delete by query](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html)

**Comment by jnothman** [comment]
oh. I'm surprised we're not forwarding the `/weedid/` component of the path. Shouldn't we, in case we happen to have multiple indexes on the server (for one of several reasons)?

**Pull request merged**
