### PR TITLE
Reorganise filters in frontend

### LINKED ISSUE #25: Export to ElasticSearch should add a field describing the tasks that can be performed with the annotation
So we should be producing in each image one or more "annotation_types" labels from:
* "classification"
* "bounding box"
* "segmentation"
* "instance segmentation"

We should be able to infer the from the annotations associated with each image....

### PR DESCRIPTION
**Pull request by jnothman**
Avoid ambiguous subject of "growth stage" and "species"

Also some more filters: task type (Fixes #25), lighting, etc.

Also disable search box for most filters.

### CODE REVIEW

**Comment by jnothman** [comment]
Changed my mind. This is draft again.

**Comment by hlydecker** [comment]
Hmmm. I wonder if it would be clearer if we did some processing at the indexing level to make it so that we can have separate weed and crop filters... OR maybe species and role filters

**Comment by jnothman** [comment]
Some more filters: task type (Fixes #25), lighting, etc.

Also disable search box for most filters.

**Review by hlydecker — APPROVED** [review]
I like the decision to remove many of the search boxes; their behaviour was not ideal (you still had to tick the box; you couldn't hit return to make the box ticked)

**Comment by jnothman** [comment]
Thanks for the review
btw, I tried to add a filter on camera height but had issues and gave up due to time constraints. Might still be a  filter worth having.

**Pull request merged**
