### PR TITLE
scale up file size limit

### LINKED ISSUE #327: [Errno 13] Permission denied to images on upload
Upload fails when processing.

### PR DESCRIPTION
**Pull request by ElevnLi**
fixes #327

### CODE REVIEW

**Review by jnothman — COMMENTED** [review]
We should also check this max size on the backend in `upload_image`. I'd suggest defining a single value in settings, then reusing it throughout the Django component at least.

**Comment by geezacoleman** [comment]
This is working well now - I'll updated the text on the upload popup to 10MB.

**Comment by jnothman** [comment]
Another thought: it's worth adding a comment to settings.pay referencing that Django bug https://github.com/django-cms/django-filer/issues/1031 to avoid future confusion

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Review by jnothman — APPROVED** [review]

**Comment by mateoradman** [comment]
Fixed in https://github.com/django/django/pull/15505

**Pull request merged**
