### PR TITLE
Add converter from Pascal VOC to Weed COCO

### LINKED ISSUE #33: Converters for Pascal VOC datasets into Weed-COCO
Datasets on RDS are a bunch of images and VOC XML files, plus an agcontext json file and a collection json file. Given paths to all these, we need to be able to convert to Weed-COCO.

### PR DESCRIPTION
**Pull request by jnothman**
Fixes #33

Replaces #49

### CODE REVIEW

**Comment by jnothman** [comment]
I'm currently getting a red mark here because `license` is required in each Image. I'd like to disable this requirement, and discuss how we want to represent image license, if we want to beyond collection membership, in a separate issue.

**Comment by jnothman** [comment]
See #105, @hlydecker

**Review by hlydecker — APPROVED** [review]
I like the direction you are taking with the utils; it will be good to refactor as many functions as possible out of individual converters into this.

So far this looks good to me, @ElevnLi and I will expand on this with the RDS data.

**Comment by jnothman** [comment]
Thanks for the review, just need to sync this with the current schema to make the ticks green...

**Comment by jnothman** [comment]
This passes pytest locally... should be good to merge.

**Comment by jnothman** [comment]
After updating weedcoco/schema/AgContext.yaml to support EPSG:3857, I could modify Guy's agcontext file and use this to load images into ES:
```
dir=/Volumes/research-data/PRJ-iweeds/data/raw/SOLES/narrabri/2019-winter/20190728
python -m weedcoco.importers.voc --voc-dir $dir/voc --image-dir $dir/img  --category-name-map $dir/category-name-map.yaml   --collection $dir/collection.yaml --agcontext $dir/agcontext.yaml -o /tmp/coco_from_voc-test.json --validate
cat /tmp/coco_from_voc-test.json | python weedcoco/draft\ export\ to\ elastic.py --thumbnail-dir artificial | curl -vv -X POST localhost:9200/_bulk  -H 'Content-Type: application/json' --data-binary @-
```

**Pull request merged**
