### PR TITLE
Test the Weed COCOs stored in git

### PR DESCRIPTION
**Pull request by jnothman**
Use real data in the workflow

### CODE REVIEW

**Comment by jnothman** [comment]
(Personally, I'd prefer not to store those Weed COCO dumps in Git. We could generate them for validating by using the scripts in the repo, which has the added benefit of testing those scripts.)

**Comment by jnothman** [comment]
Here's what CI says:
```
✓ /github/workspace/conversion_tools/cwfid_to_json/cwfid_imageinfo.json


✗ /github/workspace/conversion_tools/deepweeds_to_json/deepweeds_imageinfo.json
REQUIRED should have required property 'agcontexts'

> 1 | {
    | ^ ☹️  agcontexts is missing here!
  2 |     "images": [
  3 |         {
  4 |             "id": 0,
```
Looks like they're not quite matching.

**Comment by hlydecker** [comment]
> Here's what CI says:
> 
> ```
> ✓ /github/workspace/conversion_tools/cwfid_to_json/cwfid_imageinfo.json
> 
> 
> ✗ /github/workspace/conversion_tools/deepweeds_to_json/deepweeds_imageinfo.json
> REQUIRED should have required property 'agcontexts'
> 
> > 1 | {
>     | ^ ☹️  agcontexts is missing here!
>   2 |     "images": [
>   3 |         {
>   4 |             "id": 0,
> ```
> 
> Looks like they're not quite matching.

Interesting; I checked the two .py converters and they both create agcontext objects in the same way.

**Comment by jnothman** [comment]
> Interesting; I checked the two .py converters and they both create agcontext objects in the same way.

The key in deepweeds is "agcontext", not "agcontexts"

**Comment by hlydecker** [comment]
These now work; I checked and both converters produced identical outputs that had "agcontext" without the s. I changed both converters to create "agcontexts" objects instead of "agocontext" ones. Now it works!

**Comment by jnothman** [comment]
Woah! We have a green tick!!

**Pull request merged**
