### PR TITLE
Print tracebacks in celery tasks; store whole status details

### LINKED ISSUE #305: max_length=50 is too small on status_details
It should be a variable-length TextField

### LINKED ISSUE #306: traceback of errors in celery tasks need to be logged
Currently they're going into status_details, but we also need traceback.print_exc() there to log the full traceback for debugging purposes.

### PR DESCRIPTION
**Pull request by jnothman**
Fixes #305 
fixes #306

### CODE REVIEW

**Comment by ElevnLi** [comment]
The status_details will be showing in the upload page, which means an actual error message will break the frontend. So there should be a function that somehow summarise or categorise the error with the right info.

**Comment by jnothman** [comment]
In what way will it break the frontend? Do you mean it is too much content? I'm fine for large content to have an ellipsis ("...") and show on hover in a popup, or for it to scroll.

**Comment by jnothman** [comment]
We can't afford at this point to either summarise all possible errors, nor display no indication of the error.

**Comment by ElevnLi** [comment]
Do we merge this?

**Comment by jnothman** [comment]
Yes

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
