### PR TITLE
Enum must be an array and other schema failures

### LINKED ISSUE #70: Validate JSON failing on master
```
schema AgContext.json is invalid
error: schema is invalid: data.properties['location_datum'].enum should be array
```

### PR DESCRIPTION
**Pull request by jnothman**
Fixes #70

### CODE REVIEW

**Comment by hlydecker** [comment]
Interesting new error:

```
[ { keyword: 'pattern',
    dataPath: '.agcontexts[0].bbch_code',
    schemaPath:
     'https://weedid.sydney.edu.au/schema/AgContext.json#//properties/bbch_code/pattern',
    params: { pattern: '^gs(?!00)[0-9][0-9]$|^na$' },
    message: 'should match pattern "^gs(?!00)[0-9][0-9]$|^na$"' } ]
../conversion_tools/deepweeds_to_json/deepweeds_imageinfo.json valid
##[error]Process completed with exit code 1.
```

**Comment by jnothman** [comment]
Ahhh I was confused by you missing out the line "../conversion_tools/cwfid_to_json/cwfid_imageinfo.json invalid". cwfid has bbch_code = "GS10-19".

**Comment by hlydecker** [comment]
Yeah both this and the previous issue with the datum object are a symptom of the same disease: updates occurring off master but not being merged in because they are part of a larger branch.

**Comment by jnothman** [comment]
> Yeah both this and the previous issue with the datum object are a symptom of the same disease: updates occurring off master but not being merged in because they are part of a larger branch.

I don't understand exactly. You saying that one branch was merged and another branch was merged, and their integration was not tested with CI?

The issue here, though, is that CWFID does actually have an invalid bbch_code. What _should_ it be?

**Comment by hlydecker** [comment]
> > Yeah both this and the previous issue with the datum object are a symptom of the same disease: updates occurring off master but not being merged in because they are part of a larger branch.
> 
> I don't understand exactly. You saying that one branch was merged and another branch was merged, and their integration was not tested with CI?
> 
> The issue here, though, is that CWFID does actually have an invalid bbch_code. What _should_ it be?

Oh I think I didn't understand what was happening. Scratch what I said. 

Re the bbch_code, I changed that. The old one we had was a hold over from a previous representation of bbch_code.

**Comment by jnothman** [comment]
It expects lowercase (for good or bad)

**Comment by hlydecker** [comment]
I saw that and changed to lower case; still doesn't work. However in going back to the CWFID paper just to make sure I had recorded it right, I reread their description of crop stage: 

> The growth stage of the
> crop was approximately BBCH 10 – 20 (see [15] for a description of the BBCH
> plant growth stage scale) and a significant amount of close-to-crop and intra-row
> weeds was present.

We currently have it set to just allow one BBCH code or NA... but should we support a range of BBCH codes?

**Comment by jnothman** [comment]
> We currently have it set to just allow one BBCH code or NA... but should we support a range of BBCH codes?

You need to speak to the Ag people about that... And think about how you would search for data in a particular range. We could also consider specific ranges, e.g. GS1x. I'm not sure whether their specification of 10-20 is inclusive of 20. I suppose so?

**Pull request merged**
