### PR TITLE
Adding routing and login to search app

### PR DESCRIPTION
**Pull request by hlydecker**
Added login page

Split the website into multiple different .js files

### CODE REVIEW

**Comment by hlydecker** [comment]
I see there is a package-lock.json file: currently we have been using yarn for our package manager; have you set this up with npm? We need to make sure that we use the same package manager to prevent some issues (even though npm and yarn share many features).

Would there be any advantage to using npm over yarn?

**Comment by hlydecker** [comment]
Currently I'm unable to build the frontend locally:

```./src/index.js
Module not found: Can't resolve 'react-router-dom' in '/code/src'```

I have react-router-dom in my node_modules, and the correct version shows up when I check

**Comment by jnothman** [comment]
yes, package-lock.json seems to have accidentally reappeared in the final version of #51, but we're definitely using Yarn in the Docker build. So I'll do us a favour and remove package-lock.json in master, then we need to use `yarn add react-router-dom` in this PR.

Maybe it was misguided of me to adopt yarn, but it seems to be quite popular in practice.

**Review by jnothman — COMMENTED** [review]
I think this might be missing the point of what we need, in that it's not protecting the data from users that should not have access to it. Indeed, in the future, the database index might be open to view.

This is, however, useful infrastructure for when we want user sessions or roles.

For now, it might be simplest still to just put in HTTP Basic Authentication per #92, either with a single username and password, or with an admin-mediated list of authorised usernames and passwords.

**Review by jnothman — COMMENTED** [review]
A comment: I'm a little worried about the potential for merge conflicts here, @ElevnLi. Moving things to different files (esp. the creation of reactive_search.js) is best done in a separate PR, so that updates to it can then be merged smoothly. If we don't do that refactoring first, then every time App.js is updated in master, this will need the changes moved across to reactive_search.js.

**Comment by ElevnLi** [comment]
In that way, I'll keep the authorised user and password in the state at the beginning and don't allow users to touch that part, so basically just disabling the registration where users can modify the valid credential.

**Comment by ElevnLi** [comment]
In terms of merging it, is it enough to just have a separate commit and pull request to create the reactive_search.js, as the branches split from master previously will always track the changes on App.js?

**Comment by jnothman** [comment]
yes, doing the split to create reactive_search.js in a separate PR is ideal.

**Comment by jnothman** [comment]
I finally gave this a whirl. Opening / redirects me to /search, which is fine, and maybe this should be the more limited goal of #127.

I'm not getting any login prompts in the frontend unless I visit /login explicitly, and yet I don't think this is really showing anything to our clients / others yet, so I'd rather leave those components out for now. Splitting the login content from the refactoring and redirect content still remains a good idea.

**Comment by hlydecker** [comment]
So I followed Joel's advice to rebuild my docker containers. I did this using `docker-compose up --build`. It directs to a login page; I was able to make a user account and login. Looks nice. A logout button would be nice, but that is obviously not a priority now.

**Comment by jnothman** [comment]
Oh, I didn't get a nice login page. I wonder what's going on.

But I also think that this might be going in the wrong direction, in that we want to emphasise that, in the future, large chunks of this web site will be open and findable, not mediated by login. So login protection on the *entirety* of the content is a temporary, demo thing.

**Comment by ElevnLi** [comment]
There's a bit of misunderstanding...
When we show registration or login to the client, we are definitely not trying to say that everything will be open in the future, which is against the purpose of authentication. We just show the basic workflow of logging in and tell them there could be an admin handling different access level of different users and these concepts would be implemented in an appropriate and secure way.
From my experience, authentication cannot be done legitimately just by frontend. There should have at least a third party authorisation provider (okta or auto0) to handle the login, or a local backend server and a database server sitting in the same vm, or microservices on cloud that takes api to do the authorisation work. Correct me if I‘m wrong. Also, the login status and registered users have to be stored somewhere. In this case, they are stored in client side because there's currently nowhere else to store, not because everything supposed to be open.

**Comment by jnothman** [comment]
I've tried a rebuild and I'm still just finding the login page if I explicitly go to it:
image

I agree that there's been some misunderstanding. I see a few two purposes to implementing some kind of authentication:
1. limit access to the database under development
2. limit access to data depending on license agreement
3. store state per user
4. provide role-based capabilities such as curation

Unless I'm much mistaken, this PR more-or-less implements 3, towards demonstrating support for 2 and 4. OTOH, I feel that our most immediate needs are 1 and 2.

In the future, I expect that 2, 3 and 4 would be best managed by having a backend NoSQL database manage user state data and access, and ideally we'd provide login through external oauth SSO providers (e.g. ORCID or Google). We might be able to manage requirement 1 by having an admin authorising accounts.

Does that make sense?

**Comment by ElevnLi** [comment]
Hey Joel, the latest changes are in this commit: b4427fd. I think you pulled from f3da617, which is just the routing without login and registration.

**Comment by jnothman** [comment]
True, my mistake

**Comment by ElevnLi** [comment]
That definitely makes sense, but I don't know in terms of implementing a simple HTTP Basic Auth, where is the right place that we store the user credentials? Now I'm using state and localstorage of client side. Do you have any resource that I can have a look at? I used to do authentication with Django admin and user role, OKTA and Azure Active Directory SSO so I got a bit lost to do it purely with frontend. My understanding is that it always involves backend in some way.

**Comment by jnothman** [comment]
On other projects that I've just wanted to keep closed, I've stored basic auth in an env variable or a file, but only used a single username/password shared among all.

Seeing as we're not going to get the demo deployed publicly tomorrow, we can consider merging this PR. But then we might want to add backend authentication functionality, so that we can at least track who has access (but not block access if that's okay with our clients).

**Comment by jnothman** [comment]
Superseded

**Pull request closed without merging**
