### PR TITLE
When indexing, remove 'variable' where it creates type conflicts

### LINKED ISSUE #61: Will need an explicit schema on ElasticSearch; or change "variable" and "na" into NULL
ES seems to have done some type sniffing, which is a problem for something like `camera_fov`, since it is detected as a numeric type, and then a later dataset might say "variable" and it breaks. The other option might be to store "variable" as null in the index, thus avoiding the problem (currently implemented in #49).

https://github.com/kristianmandrup/json-schema-to-es-mapping might help. I've only found it, not looked at it.

### PR DESCRIPTION
**Pull request by jnothman**
Pulled out of #49
Fixes #61

### CODE REVIEW

**Review by hlydecker — COMMENTED** [review]
I'm still not a fan of how Elasticsearch is handling this. I suppose it would make sense if we actually had  a range of values for an agcontext (i.e. some images have ` fov: 50 ` and others have ` fov: 30 `.

**Comment by jnothman** [comment]
My perspective is that:
1. AgContext should contain values that are usually fixed across an image capture process
2. If a dataset contains multiple image capture processes, it should have multiple AgContexts

But if it's reasonable for someone to do processing on the images that modifies the FOV, then it would be unreasonable to enforce the second criterion.

**Comment by jnothman** [comment]
But I've had enough of this project for the week, so please feel free to review, but I won't do much with it until I come back from leave on Wed.

**Comment by hlydecker** [comment]
> My perspective is that:
> 
> 1. AgContext should contain values that are usually fixed across an image capture process
> 2. If a dataset contains multiple image capture processes, it should have multiple AgContexts
> 
> But if it's reasonable for someone to do processing on the images that modifies the FOV, then it would be unreasonable to enforce the second criterion.

Then we pretty much have the same perspective here. I could see some users deciding to mix FOVs and do some sort of image processing to make them the same FOV, but I think it is reasonable for each agcontext to have one FOV.

**Comment by hlydecker** [comment]
> But I've had enough of this project for the week, so please feel free to review, but I won't do much with it until I come back from leave on Wed.

You have a been very productive! Have some nice rest if you can while you are on leave :) I'll review your progress and work on my issues while you are gone.

**Pull request merged**
