### PR TITLE
Make weedcoco into a Python package

### PR DESCRIPTION
**Pull request by jnothman**
I've moved a lot of things around. Making conversion_tools + other into a package called weedcoco. I've got a dummy stub for a module called weedcoco.validation. The importers are now modules weedcoco.importers.deepweeds (although currently they're not safe to import since they only run on command-line).

Work in progress. Probably broken right now. Thoughts, @hlydecker?

### CODE REVIEW

**Comment by hlydecker** [comment]
I like the idea here, I feel like moving this direction can help with developing future converters because it will encourage us to draw from a toolkit of common functions rather than reinventing the wheel each time and potentially introducing conflicts.

**Comment by jnothman** [comment]
Yes, I forgot to say that refactoring to use components for #49 was the motivation here.

**Comment by jnothman** [comment]
I'm happy with this as a first step. What's still to do is that it keeps the cwfid_to_json and deepweeds_to_json directories, which I'd be happy to get rid of.

**Comment by hlydecker** [comment]
> I'm happy with this as a first step. What's still to do is that it keeps the cwfid_to_json and deepweeds_to_json directories, which I'd be happy to get rid of.

Yeah it doesn't make as much sense to store those directories in there.

We had discussed storing a small subset of images and annotations for each dataset to validate conversion; would this be something to include in the package?

**Comment by jnothman** [comment]
>  We had discussed storing a small subset of images and annotations for each dataset to validate conversion; would this be something to include in the package?

If it's part of the test suite, then maybe. There are two schools of thought about whether tests should be in a package.

**Comment by jnothman** [comment]
Let's leave the testing and associated cleaning of #74 to another PR. This one is ready for review. Thanks

**Comment by hlydecker** [comment]
Sorry, didn't mean to give that a "thumbs down"! I've looked through your changes, and I like the rationale. Nothing jumped out at me as being problematic, and it is good to see that conversion still works as part of our validation workflows with these changes.

**Review by hlydecker — APPROVED** [review]
I'm happy with the way this is working both in workflow and locally. It will be good for me to spend some time looking at our existing converters and seeing what else can be made universal. Perhaps an agcontext builder function that will read that yaml template...

**Pull request merged**
