### PR TITLE
separate file for reactive_search.js

### PR DESCRIPTION
**Pull request by ElevnLi**
This creates the separate file of reactive search for routing

### CODE REVIEW

**Comment by jnothman** [comment]
So I think you also need to update App.js to remove this content from there, and instead to import the component. Ideally git recognises that most of the file's content was moved.

**Comment by ElevnLi** [comment]
Can I also add the other components, login and registration? There will be importing these two from App.js, but in that way it would be basically the same as the other pull request.

**Comment by jnothman** [comment]
Yes, it would be the same as the other PR. The idea is to separate out the new content from the refactoring. But maybe I should just not worry about it and look at the other PR as it stands.

**Comment by ElevnLi** [comment]
Should I cherry pick from f3da617 and pull request, as that is the file changes commit?

**Pull request merged**
