### PR TITLE
Ag context form tool

### LINKED ISSUE #146: Agcontext editor form
Research options for react form entry options and develop a tool to allow users to create and export an AgContext yaml based on what they have entered into the form.

### PR DESCRIPTION
**Pull request by hlydecker**
Closes #146

### CODE REVIEW

**Comment by hlydecker** [comment]
When submitting a form, this is the console message: 
image

There's probably a simple solution via useState and formData

**Comment by hlydecker** [comment]
Testing out material ui; looks promising https://react-jsonschema-form-material-ui.github56.now.sh/

**Comment by hlydecker** [comment]
> Testing out material ui; looks promising https://react-jsonschema-form-material-ui.github56.now.sh/

From playing around with their sandbox it looks like their pretty UI depends on you including a lot of the UI structure in the json schema itself... lame

**Comment by jnothman** [comment]
> From playing around with their sandbox it looks like their pretty UI depends on you including a lot of the UI structure in the json schema itself... lame

Yes, it looks like they're really adopting jsonschema as a way to facilitate declarative form specification that will give them corresponding JSON data, not so much focused on a public API/interchange format.
For our purposes, the master format of the schema could be the one with the styling, and we could strip the styling information if we want to publish the schema as a schema??

**Comment by jnothman** [comment]
Commit your latest changes?

**Review by jnothman — COMMENTED** [review]
Maybe you've fixed these by now

**Comment by jnothman** [comment]
I've marked this ready for review... additional work will be in other PRs:
* load schemas from `weedcoco/schema/*` rather than by duplicating them in `search/src/schemas.js`
* make input formdata a parameter of the component
* have optional input/output using a text box
* group form elements semantically
* remove/hide input for `id` and allocate ordinally
* improve UI for entering growth stage codes

**Comment by jnothman** [comment]
Hmm. I'm now having trouble getting this to render. I must be doing something wrong. :|

**Comment by jnothman** [comment]
Work on jsonforms and growth stage selector are currently happening here: https://github.com/jnothman/jsonforms-react-seed-agcontext/tree/master/src

**Comment by jnothman** [comment]
I'm aiming to give the jsonforms solution a similar component API to the current form here, but it provides much more control over display.

**Comment by jnothman** [comment]
jsonforms allows styling like:
image

**Comment by jnothman** [comment]
merged to master as part of #193

**Pull request closed without merging**
