### PR TITLE
dejavu removal

### PR DESCRIPTION
**Pull request by hlydecker**
remove dejavu 

solves #106

### CODE REVIEW

**Review by jnothman — APPROVED** [review]
have you got something auto-formatting your yamls? I'm guessing this is a VS code plugin.
Apart from all the unrelated changes that would usually not be advisable (because they create merge conflicts), this LGTM

**Comment by hlydecker** [comment]
> have you got something auto-formatting your yamls? I'm guessing this is a VS code plugin.
> Apart from all the unrelated changes that would usually not be advisable (because they create merge conflicts), this LGTM

I'll disable that auto-format on save for YAMLs to help us avoid that :)

**Comment by jnothman** [comment]
> I'll disable that auto-format on save for YAMLs to help us avoid that :)

Alternatively, update all the yaml files here to conform, and add it to our pre-commit config.

**Comment by hlydecker** [comment]
Just had a look at yaml linter github actions; there are 38 different ones available?

**Comment by jnothman** [comment]
Not a priority.

**Pull request merged**
