### PR TITLE
Display data in a predetermined random order

### PR DESCRIPTION
**Pull request by jnothman**

### CODE REVIEW

**Comment by jnothman** [comment]
image

**Comment by jnothman** [comment]
Hmm... we should disregard codecov on "draft export to elastic.py"

**Comment by hlydecker** [comment]
Looks good. Would we also want to sort so that images with wheat appear first? Or perhaps even a set selection of nice looking wheat?

**Comment by jnothman** [comment]
I think being able to filter on crop type (see #116) will suffice for now?

**Review by hlydecker — COMMENTED** [review]
looks good.

**Pull request merged**
